/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=production --include-runtime=false worker/env.d.ts` (hash: e5b0f24f5b3b83e33d103f756507cf57)
interface __BaseEnv_Env {
  DEMO_RATE_LIMIT: RateLimit;
  DEMO_BACKEND: Fetcher;
  ASSETS: Fetcher;
  DEMO_ORIGIN: 'http://instantkv-demo.internal';
  DEMO_GATEWAY_TOKEN: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./index');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'DEMO_ORIGIN' | 'DEMO_GATEWAY_TOKEN'>
  > {}
}
