/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=production --include-runtime=false worker/env.d.ts` (hash: 5437b83e1764e96edc54a1c9e9892501)
interface __BaseEnv_Env {
  DEMO_RATE_LIMIT: RateLimit;
  ASSETS: Fetcher;
  DEMO_ORIGIN: 'https://45.196.196.251/instantkv-demo';
  DEMO_GATEWAY_TOKEN: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./index');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'DEMO_ORIGIN' | 'DEMO_GATEWAY_TOKEN'>
  > {}
}
