/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false worker/env.d.ts` (hash: 7b56ea91f812cc706ad0886f1f15677f)
interface __BaseEnv_Env {
  ASSETS: Fetcher;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./index');
  }
  interface ProductionEnv {
    ASSETS: Fetcher;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
