[package]
name = "instantkv-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Policy, storage, and atomic checkpoint engine for instantKV"
publish.workspace = true

[dependencies]
serde.workspace = true
toml.workspace = true
serde_json.workspace = true
redb.workspace = true
thiserror.workspace = true
schemars.workspace = true
rust-stemmers = "1.2"

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
